version: "3.3"
services:
    analyze:
        image: "nginx:stable-alpine"
        container_name: analyze_server
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php
        networks:
            - main_net
    php:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
        container_name: analyze_php
        volumes:
            - ./:/var/www/html
        networks:
            - main_net
    composer:
        build:
            context: ./dockerfiles
            dockerfile: composer.dockerfile
        container_name: analyze_composer
        volumes:
            - ./:/var/www/html
    artisan:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
        volumes:
            - ./:/var/www/html
        entrypoint: ["php", "/var/www/html/artisan"]
networks:
    main_net:
        external: true
