version: "3.8"

services:
    analyze:
        image: "nginx:stable-alpine"
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

    php:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
        volumes:
            - ./:/var/www/html:delegated
